name: workspace deployment
on:
    workflow_dispatch:
    push:
        branches: 
          - workspace_publish
jobs:
    deployworkspace:
        # You also can use the self-hosted runners.
        runs-on: windows-latest
        steps:
        # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
        - uses: actions/checkout@v2
        - uses: Azure/Synapse-workspace-deployment@V1.9.1
          with:
            # Provide the Synapse workspace name where you want to deploy the artifacts.
            TargetWorkspaceName: 'testforsynapsehongwei'
            # Specify the path to the workspace artifacts template.
            TemplateFile: '' 
            # Specify the path to the template parameter file.
            ParametersFile: ''
            # Specify deployment parameter values.
            OverrideArmParameters: # optional, default is 
            # Provide the type of cloud environment. Valid values are: Azure Public, Azure China, Azure US Government, Azure Germany
            Environment: 'Azure China'
            # Provide the resource group of the target Synapse workspace.
            resourceGroup: ${{AZURE_SYNAPSE_GROUP}}
            # Provide client id of service principal.
            clientId: ${{AZURE_CLIENT_ID}}  # optional
            # Provide client secret of the service principal.
            clientSecret: ${{secrets.CLIENTSECRET}}   # optional
            # Provide subscription id.
            subscriptionId: ${{AZURE_SUBSCRIPTION_ID}}
            # Provide tenant id.
            tenantId: ${{AZURE_TENANT_ID}} 
            # Delete the artifacts which are in the workspace but not in the template.
            DeleteArtifactsNotInTemplate: # optional
            # Use managed identity to generate the bearer token?
            managedIdentity: # optional
            # Deploy managed private endpoints in the template.
            deployManagedPrivateEndpoint: # optional
            # Mark the pipeline as failed if ARM overrides are missing.
            FailOnMissingOverrides: # optional
            # Provide path to the root folder.
            ArtifactsFolder: # optional
            # Provide name of the operation.
            operation: 
            # Source for the npm package. Only for dev testing.
            npmpackage: # optional
          
